### PR TITLE
readme test

### PR DESCRIPTION
**Pull request by Erdemg**
## Purpose

* ...
[AB#5](https://dev.azure.com/OpenHack11/88319bfc-1cd4-490b-9610-279555dd66fa/_workitems/edit/5)

## Does this introduce a breaking change?

```
[ ] Yes
[ X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Review by alschroe — APPROVED** [review]

**Review by astaykov — COMMENTED** [review]
Why this change? 
I do not see this change as necessary ;)

**Comment by astaykov** [comment]
@Erdemg please add a reference to Work Item 5 in your comment!
You can use the following syntax: `[AB#5](https://dev.azure.com/OpenHack11/88319bfc-1cd4-490b-9610-279555dd66fa/_workitems/edit/5)`

This means you have to make new change and submit new pull request

**Comment by Erdemg** [comment]
[AB#5](https://dev.azure.com/OpenHack11/88319bfc-1cd4-490b-9610-279555dd66fa/_workitems/edit/5)

**Review by astaykov — APPROVED** [review]
Approved (hidden in the right hand menu ;) )

**Pull request merged**
